### ISSUE TITLE
Числа 7 и 8

### ISSUE THREAD

**Issue by TalantRys** [pivsemdmi/phone-mask-js#1]
**Нашёл следующие баги:**
1. Написать максимум символов можно всеми числами кроме 7 и 8. На них не работает лимит.
Например, если заполнить поле цифрами 7 или 8 и в конце поставить любое число, то это число можно сдвинуть, снова написав 7 или 8.
2. Если заполнить поле только 7 или 8, то можно всё равно добавить число, несмотря на лимит

**Comment by pivsemdmi** [comment]
Это фича
> Trimming [87] numbers in beginning of unmasked phone number when overflowed

Можно отключить опцией `trimUnmask`, установив в положение `false`

**Comment by TalantRys** [comment]
в примере не увидел🤔ну ок
